Added security policy and code of conduct.
CSE-25/amrita_pyq pull request #11
Opened 2024-10-31 10:22 UTC by Abhinav-ark

2024-10-31 10:55 UTC, Ashrockzzz2003 requested changes

2024-10-31 10:55 UTC, Ashrockzzz2003 commented on SECURITY.md
> +Report security vulnerabilities by emailing the Amrita PYQ team at <a href="mailto:abhinavramki2@gmail.com">abhinavramki2@gmail.com</a> or
Creating issues and tagging us here is enough?

2024-10-31 15:43 UTC, Ashrockzzz2003 commented
Also @Abhinav-ark 
Can you add these files inside a `.github` directory? It will make it easy to isolate from project files.
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

2024-10-31 17:37 UTC, Abhinav-ark commented
> Also @Abhinav-ark Can you add these files inside the `.github` directory? It will make it easy to isolate from project files. https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

This will be shown in repo home page aside readme only if it is in root folder. Contributing.md we can move to docs directory.
![image](https://github.com/user-attachments/assets/b9f7433d-a67c-4a03-a7af-61021614287c)

2024-10-31 17:47 UTC, Abhinav-ark commented on SECURITY.md
> +Report security vulnerabilities by emailing the Amrita PYQ team at <a href="mailto:abhinavramki2@gmail.com">abhinavramki2@gmail.com</a> or
Isn't it preferrable to report security vulnerabilities privately? Publicly announcing them might expose security vulnerabilities to parties with malicious intent who had no idea about them in the first place.

2024-11-01 03:32 UTC, Ashrockzzz2003 approved these changes
LGTM

2024-11-01 03:32 UTC, merged